entity_common.o: entity_common.c \
 ../gf3d/gfc/simple_logger/include/simple_logger.h \
 ../include/entity_common.h ../gf3d/include/gf3d_entity.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/gfc/include/gfc_color.h \
 ../gf3d/gfc/include/gfc_vector.h ../gf3d/gfc/include/gfc_types.h \
 ../gf3d/gfc/include/gfc_primitives.h \
 ../gf3d/gfc/simple_json/include/simple_json.h \
 ../gf3d/gfc/simple_json/include/simple_json_list.h \
 ../gf3d/gfc/simple_json/include/simple_json_string.h \
 ../gf3d/gfc/simple_json/include/simple_json_types.h \
 ../gf3d/gfc/simple_json/include/simple_json_object.h \
 ../gf3d/gfc/simple_json/include/simple_json_value.h \
 ../gf3d/gfc/simple_json/include/simple_json_error.h \
 ../gf3d/gfc/include/gfc_matrix.h ../gf3d/gfc/include/gfc_color.h \
 ../gf3d/gfc/include/gfc_shape.h ../gf3d/include/gf2d_body.h \
 ../gf3d/gfc/include/gfc_list.h ../gf3d/gfc/include/gfc_text.h \
 ../gf3d/include/gf2d_actor.h ../gf3d/gfc/include/gfc_vector.h \
 ../gf3d/include/gf2d_sprite.h ../gf3d/gfc/include/gfc_matrix.h \
 ../gf3d/include/gf3d_pipeline.h ../gf3d/include/gf3d_uniform_buffers.h \
 ../gf3d/include/gf3d_texture.h ../gf3d/include/gf3d_model.h \
 ../gf3d/include/gf3d_mesh.h
game.o: game.c ../gf3d/gfc/simple_logger/include/simple_logger.h \
 ../gf3d/gfc/include/gfc_list.h ../gf3d/gfc/include/gfc_audio.h \
 ../gf3d/gfc/simple_json/include/simple_json.h \
 ../gf3d/gfc/simple_json/include/simple_json_list.h \
 ../gf3d/gfc/simple_json/include/simple_json_string.h \
 ../gf3d/gfc/simple_json/include/simple_json_types.h \
 ../gf3d/gfc/simple_json/include/simple_json_object.h \
 ../gf3d/gfc/simple_json/include/simple_json_value.h \
 ../gf3d/gfc/simple_json/include/simple_json_error.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/gfc/include/gfc_text.h \
 ../gf3d/gfc/include/gfc_color.h ../gf3d/gfc/include/gfc_vector.h \
 ../gf3d/gfc/include/gfc_list.h ../gf3d/gfc/include/gfc_hashmap.h \
 ../gf3d/gfc/include/gfc_input.h ../gf3d/gfc/include/gfc_pak.h \
 ../gf3d/include/gf3d_vgraphics.h ../gf3d/gfc/include/gfc_vector.h \
 ../gf3d/gfc/include/gfc_matrix.h ../gf3d/include/gf3d_pipeline.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/include/gf3d_uniform_buffers.h \
 ../gf3d/include/gf3d_texture.h ../gf3d/gfc/include/gfc_text.h \
 ../gf3d/include/gf3d_commands.h ../gf3d/include/gf2d_camera.h \
 ../gf3d/gfc/include/gfc_shape.h ../gf3d/include/gf3d_texture.h \
 ../gf3d/include/gf3d_entity.h ../gf3d/gfc/include/gfc_color.h \
 ../gf3d/gfc/include/gfc_primitives.h ../gf3d/gfc/include/gfc_matrix.h \
 ../gf3d/include/gf2d_body.h ../gf3d/include/gf2d_actor.h \
 ../gf3d/include/gf2d_sprite.h ../gf3d/include/gf3d_model.h \
 ../gf3d/include/gf3d_mesh.h ../gf3d/include/gf3d_cliplayers.h \
 ../gf3d/include/gf2d_sprite.h ../gf3d/include/gf2d_font.h \
 ../gf3d/include/gf2d_draw.h ../gf3d/include/gf2d_actor.h \
 ../gf3d/include/gf2d_mouse.h ../gf3d/include/gf2d_windows.h \
 ../gf3d/include/gf2d_windows_common.h ../gf3d/include/gf2d_windows.h \
 ../include/hive.h ../include/level.h ../gf3d/include/gf2d_space.h \
 ../include/player.h
hive.o: hive.c ../gf3d/gfc/simple_logger/include/simple_logger.h \
 ../gf3d/include/gf3d_vgraphics.h ../gf3d/gfc/include/gfc_vector.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/gfc/include/gfc_matrix.h \
 ../gf3d/gfc/include/gfc_vector.h ../gf3d/include/gf3d_pipeline.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/include/gf3d_uniform_buffers.h \
 ../gf3d/include/gf3d_texture.h ../gf3d/gfc/include/gfc_text.h \
 ../gf3d/gfc/include/gfc_color.h ../gf3d/include/gf3d_commands.h \
 ../gf3d/include/gf2d_draw.h ../gf3d/gfc/include/gfc_list.h \
 ../gf3d/gfc/include/gfc_shape.h \
 ../gf3d/gfc/simple_json/include/simple_json.h \
 ../gf3d/gfc/simple_json/include/simple_json_list.h \
 ../gf3d/gfc/simple_json/include/simple_json_string.h \
 ../gf3d/gfc/simple_json/include/simple_json_types.h \
 ../gf3d/gfc/simple_json/include/simple_json_object.h \
 ../gf3d/gfc/simple_json/include/simple_json_value.h \
 ../gf3d/gfc/simple_json/include/simple_json_error.h \
 ../gf3d/gfc/include/gfc_color.h ../gf3d/include/gf2d_camera.h \
 ../include/level.h ../gf3d/include/gf3d_entity.h \
 ../gf3d/gfc/include/gfc_primitives.h ../gf3d/gfc/include/gfc_matrix.h \
 ../gf3d/include/gf2d_body.h ../gf3d/include/gf2d_actor.h \
 ../gf3d/include/gf2d_sprite.h ../gf3d/include/gf3d_model.h \
 ../gf3d/include/gf3d_mesh.h ../gf3d/include/gf2d_space.h \
 ../gf3d/include/gf2d_sprite.h ../include/space_bug.h ../include/hive.h
level.o: level.c ../gf3d/gfc/simple_logger/include/simple_logger.h \
 ../gf3d/gfc/simple_json/include/simple_json.h \
 ../gf3d/gfc/simple_json/include/simple_json_list.h \
 ../gf3d/gfc/simple_json/include/simple_json_string.h \
 ../gf3d/gfc/simple_json/include/simple_json_types.h \
 ../gf3d/gfc/simple_json/include/simple_json_object.h \
 ../gf3d/gfc/simple_json/include/simple_json_value.h \
 ../gf3d/gfc/simple_json/include/simple_json_error.h \
 ../gf3d/gfc/include/gfc_config.h ../gf3d/gfc/include/gfc_vector.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/gfc/include/gfc_color.h \
 ../gf3d/gfc/include/gfc_list.h ../gf3d/include/gf3d_vgraphics.h \
 ../gf3d/gfc/include/gfc_vector.h ../gf3d/gfc/include/gfc_matrix.h \
 ../gf3d/include/gf3d_pipeline.h ../gf3d/gfc/include/gfc_types.h \
 ../gf3d/include/gf3d_uniform_buffers.h ../gf3d/include/gf3d_texture.h \
 ../gf3d/gfc/include/gfc_text.h ../gf3d/include/gf3d_commands.h \
 ../gf3d/include/gf2d_camera.h ../gf3d/gfc/include/gfc_shape.h \
 ../include/level.h ../gf3d/include/gf3d_entity.h \
 ../gf3d/gfc/include/gfc_color.h ../gf3d/gfc/include/gfc_primitives.h \
 ../gf3d/gfc/include/gfc_matrix.h ../gf3d/include/gf2d_body.h \
 ../gf3d/include/gf2d_actor.h ../gf3d/include/gf2d_sprite.h \
 ../gf3d/include/gf3d_model.h ../gf3d/include/gf3d_mesh.h \
 ../gf3d/include/gf2d_space.h ../gf3d/include/gf2d_sprite.h
player.o: player.c ../gf3d/gfc/simple_logger/include/simple_logger.h \
 ../gf3d/gfc/include/gfc_input.h ../gf3d/gfc/include/gfc_text.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/gfc/include/gfc_color.h \
 ../gf3d/gfc/include/gfc_vector.h ../gf3d/gfc/include/gfc_list.h \
 ../gf3d/include/gf3d_vgraphics.h ../gf3d/gfc/include/gfc_vector.h \
 ../gf3d/gfc/include/gfc_matrix.h ../gf3d/include/gf3d_pipeline.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/include/gf3d_uniform_buffers.h \
 ../gf3d/include/gf3d_texture.h ../gf3d/gfc/include/gfc_text.h \
 ../gf3d/include/gf3d_commands.h ../gf3d/include/gf2d_draw.h \
 ../gf3d/gfc/include/gfc_list.h ../gf3d/gfc/include/gfc_shape.h \
 ../gf3d/gfc/simple_json/include/simple_json.h \
 ../gf3d/gfc/simple_json/include/simple_json_list.h \
 ../gf3d/gfc/simple_json/include/simple_json_string.h \
 ../gf3d/gfc/simple_json/include/simple_json_types.h \
 ../gf3d/gfc/simple_json/include/simple_json_object.h \
 ../gf3d/gfc/simple_json/include/simple_json_value.h \
 ../gf3d/gfc/simple_json/include/simple_json_error.h \
 ../gf3d/gfc/include/gfc_color.h ../gf3d/include/gf2d_camera.h \
 ../gf3d/include/gf2d_mouse.h ../gf3d/gfc/include/gfc_primitives.h \
 ../gf3d/gfc/include/gfc_matrix.h ../gf3d/include/gf2d_actor.h \
 ../gf3d/include/gf2d_sprite.h ../include/level.h \
 ../gf3d/include/gf3d_entity.h ../gf3d/include/gf2d_body.h \
 ../gf3d/include/gf3d_model.h ../gf3d/include/gf3d_mesh.h \
 ../gf3d/include/gf2d_space.h ../gf3d/include/gf2d_sprite.h \
 ../include/projectile.h ../include/player.h
projectile.o: projectile.c \
 ../gf3d/gfc/simple_logger/include/simple_logger.h \
 ../gf3d/include/gf3d_vgraphics.h ../gf3d/gfc/include/gfc_vector.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/gfc/include/gfc_matrix.h \
 ../gf3d/gfc/include/gfc_vector.h ../gf3d/include/gf3d_pipeline.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/include/gf3d_uniform_buffers.h \
 ../gf3d/include/gf3d_texture.h ../gf3d/gfc/include/gfc_text.h \
 ../gf3d/gfc/include/gfc_color.h ../gf3d/include/gf3d_commands.h \
 ../gf3d/include/gf2d_draw.h ../gf3d/gfc/include/gfc_list.h \
 ../gf3d/gfc/include/gfc_shape.h \
 ../gf3d/gfc/simple_json/include/simple_json.h \
 ../gf3d/gfc/simple_json/include/simple_json_list.h \
 ../gf3d/gfc/simple_json/include/simple_json_string.h \
 ../gf3d/gfc/simple_json/include/simple_json_types.h \
 ../gf3d/gfc/simple_json/include/simple_json_object.h \
 ../gf3d/gfc/simple_json/include/simple_json_value.h \
 ../gf3d/gfc/simple_json/include/simple_json_error.h \
 ../gf3d/gfc/include/gfc_color.h ../gf3d/include/gf2d_camera.h \
 ../gf3d/include/gf2d_collision.h ../gf3d/include/gf2d_space.h \
 ../gf3d/include/gf2d_body.h ../include/level.h \
 ../gf3d/include/gf3d_entity.h ../gf3d/gfc/include/gfc_primitives.h \
 ../gf3d/gfc/include/gfc_matrix.h ../gf3d/include/gf2d_actor.h \
 ../gf3d/include/gf2d_sprite.h ../gf3d/include/gf3d_model.h \
 ../gf3d/include/gf3d_mesh.h ../gf3d/include/gf2d_space.h \
 ../gf3d/include/gf2d_sprite.h ../include/projectile.h
space_bug.o: space_bug.c \
 ../gf3d/gfc/simple_logger/include/simple_logger.h \
 ../gf3d/include/gf3d_vgraphics.h ../gf3d/gfc/include/gfc_vector.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/gfc/include/gfc_matrix.h \
 ../gf3d/gfc/include/gfc_vector.h ../gf3d/include/gf3d_pipeline.h \
 ../gf3d/gfc/include/gfc_types.h ../gf3d/include/gf3d_uniform_buffers.h \
 ../gf3d/include/gf3d_texture.h ../gf3d/gfc/include/gfc_text.h \
 ../gf3d/gfc/include/gfc_color.h ../gf3d/include/gf3d_commands.h \
 ../gf3d/include/gf2d_draw.h ../gf3d/gfc/include/gfc_list.h \
 ../gf3d/gfc/include/gfc_shape.h \
 ../gf3d/gfc/simple_json/include/simple_json.h \
 ../gf3d/gfc/simple_json/include/simple_json_list.h \
 ../gf3d/gfc/simple_json/include/simple_json_string.h \
 ../gf3d/gfc/simple_json/include/simple_json_types.h \
 ../gf3d/gfc/simple_json/include/simple_json_object.h \
 ../gf3d/gfc/simple_json/include/simple_json_value.h \
 ../gf3d/gfc/simple_json/include/simple_json_error.h \
 ../gf3d/gfc/include/gfc_color.h ../gf3d/include/gf2d_camera.h \
 ../gf3d/include/gf2d_collision.h ../gf3d/include/gf2d_space.h \
 ../gf3d/include/gf2d_body.h ../include/entity_common.h \
 ../gf3d/include/gf3d_entity.h ../gf3d/gfc/include/gfc_primitives.h \
 ../gf3d/gfc/include/gfc_matrix.h ../gf3d/include/gf2d_actor.h \
 ../gf3d/include/gf2d_sprite.h ../gf3d/include/gf3d_model.h \
 ../gf3d/include/gf3d_mesh.h ../include/level.h \
 ../gf3d/include/gf2d_space.h ../gf3d/include/gf2d_sprite.h \
 ../include/player.h ../include/hive.h ../include/space_bug.h
